services:
  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.diy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  calcom-api:
    container_name: calcom-api
    build:
      context: .
      dockerfile: apps/api/v2/Dockerfile
    restart: always
